[common controls]
    [GuardRail Controls]
    AWS-GR_CLOUDTRAIL_CHANGE_PROHIBITED
    AWS-GR_CLOUDTRAIL_CLOUDWATCH_LOGS_ENABLED
    AWS-GR_CLOUDTRAIL_ENABLED
    AWS-GR_CLOUDTRAIL_VALIDATION_ENABLED
    AWS-GR_CLOUDWATCH_EVENTS_CHANGE_PROHIBITED
    AWS-GR_CONFIG_AGGREGATION_AUTHORIZATION_POLICY
    AWS-GR_CONFIG_AGGREGATION_CHANGE_PROHIBITED
    AWS-GR_CONFIG_CHANGE_PROHIBITED
    AWS-GR_CONFIG_ENABLED
    AWS-GR_CONFIG_RULE_CHANGE_PROHIBITED
    AWS-GR_IAM_ROLE_CHANGE_PROHIBITED
    AWS-GR_LAMBDA_CHANGE_PROHIBITED
    AWS-GR_LOG_GROUP_POLICY
    AWS-GR_SNS_CHANGE_PROHIBITED
    AWS-GR_SNS_SUBSCRIPTION_CHANGE_PROHIBITED

    [Testgenie]
    AWS-GR_CLOUDTRAIL_ENABLED
    AWS-GR_CLOUDTRAIL_VALIDATION_ENABLED
    AWS-GR_CLOUDWATCH_EVENTS_CHANGE_PROHIBITED
    AWS-GR_CONFIG_AGGREGATION_AUTHORIZATION_POLICY
    AWS-GR_CONFIG_AGGREGATION_CHANGE_PROHI